### ISSUE TITLE
illegal_argument_exception date

### ISSUE THREAD

**Issue by Coeur-Digital** [DivanteLtd/mage2vuestorefront#101]
Hello I got 2 errors when I try to run: yarn mage2vs import
I don't understand

I run it on the same server as magento 
Without docker

Thanks

```
error: API call failed: Request does not match any route.

2020-05-21T10:33:42.389Z - error:
{
  message: 'Request does not match any route.',
  stack: 'Error: Request does not match any route.\n' +
    '    at /var/www/Store-front/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/review.js:27:13\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}``

```
error: uncaughtException: ResponseError: illegal_argument_exception date=Thu May 21 2020 12:28:45 GMT+0200 (Central European Summer Time), pid=9413, uid=0, gid=0, cwd=/var/www/Store-front/vue-storefront-api, execPath=/root/.nvm/versions/node/v12.16.3/bin/node, version=v12.16.3, argv=[/root/.nvm/versions/node/v12.16.3/bin/node, /var/www/Store-front/vue-storefront-api/node_modules/mage2vuestorefront/src/cli.js, attributes, --removeNonExistent=true], rss=73924608, heapTotal=53653504, heapUsed=19861056, external=1395436, loadavg=[0.38427734375, 0.79443359375, 0.75439453125], uptime=3184, trace=[column=15, file=/var/www/Store-front/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/nosql/elasticsearch.js, function=null, line=110, method=null, native=false, column=25, file=/var/www/Store-front/vue-storefront-api/node_modules/once/once.js, function=f, line=25, method=null, native=false, column=11, file=/var/www/Store-front/vue-storefront-api/node_modules/@elastic/elasticsearch/lib/Transport.js, function=null, line=289, method=null, native=false, column=22, file=events.js, function=IncomingMessage.emit, line=322, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=1187, method=null, native=false, column=21, file=internal/process/task_queues.js, function=processTicksAndRejections, line=84, method=null, native=false], stack=[Error: ResponseError: illegal_argument_exception,     at /var/www/Store-front/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/nosql/elasticsearch.js:110:15,     at f (/var/www/Store-front/vue-storefront-api/node_modules/once/once.js:25:25),     at IncomingMessage.<anonymous> (/var/www/Store-front/vue-storefront-api/node_modules/@elastic/elasticsearch/lib/Transport.js:289:11),     at IncomingMessage.emit (events.js:322:22),     at endReadableNT (_stream_readable.js:1187:12),     at processTicksAndRejections (internal/process/task_queues.js:84:21)]```

**Comment by gibkigonzo** [comment]
Hey, I can't tell you what is wrong. You need to debug it.That is not enough information to get answer. Stack trace from error shows that it occurs here: https://github.com/DivanteLtd/mage2vuestorefront/blob/master/src/adapters/nosql/elasticsearch.js#L110 So add here console.log with response or updateRequestBody or item.
