### ISSUE TITLE
Cannot read property 'attribute_id' of null produc t.js:256:47

### ISSUE THREAD

**Issue by kuldeepkiwitech** [DivanteLtd/mage2vuestorefront#104]
error: Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'attribute_id' of null
      at findOptionValues (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/produc
t.js:256:47)
      at /var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37
      at Array.map (<anonymous>)
      at selectFields (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js
:260:39)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
} reason: 
{
  message: "Cannot read property 'attribute_id' of null",
  stack: "TypeError: Cannot read property 'attribute_id' of null\n" +
    '    at findOptionValues (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/pro
duct.js:256:47)\n' +
    '    at /var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product.js:261:37\n' 
+
    '    at Array.map (<anonymous>)\n' +
    '    at selectFields (/var/www/html/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/product
.js:260:39)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}

**Comment by Kannas24** [comment]
any update on this?

**Comment by aman-addweb** [comment]
i'm also having same issue
